06-rails/moma/config/routes.rb
Rails.application.routes.draw do
  root :to => 'artists#index'
  resources :artists, :works
end

06-rails/moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string
#  nationality :string
#  dob         :date
#  period      :string
#  image       :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Artist < ActiveRecord::Base
  has_many :works
end

06-rails/moma/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :string
#  year       :string
#  medium     :string
#  style      :string
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#  artist_id  :integer
#

class Work < ActiveRecord::Base
  belongs_to :artist
end

06-rails/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def new
    @artist = Artist.new
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def show
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

06-rails/moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def new
    @work = Work.new
  end

  def edit
    @work = Work.find params[:id]
  end

  def show
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

06-rails/moma/app/helpers/artists_helper.rb
module ArtistsHelper
end

06-rails/moma/app/helpers/works_helper.rb
module WorksHelper
end

06-rails/moma/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>

  <%= f.label :nationality %>
  <%= f.text_field :nationality %>

  <%= f.label :dob, "Date of birth" %>
  <%= f.text_field :dob %>

  <%= f.label :period %>
  <%= f.text_field :period %>

  <%= f.label :image %>
  <%= f.url_field :image %>

  <%= f.submit  %>
<% end %>

06-rails/moma/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render :partial => 'form' %>

06-rails/moma/app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <%= image_tag(artist.image, :class => 'thumb') %>
  <ul>
    <li>Name: <%= link_to(artist.name, artist) %></li>
    <li>Nationality: <%= artist.nationality %></li>
    <li>Date of birth: <%= artist.dob.strftime('%A %B %e, %Y') %></li>
    <li>Period: <%= artist.period %></li>
  </ul>
<% end %>

06-rails/moma/app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render :partial => 'form' %>

06-rails/moma/app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<p>
  <%= link_to 'Edit artist', edit_artist_path(@artist) %>
  <%= link_to 'Delete artist', @artist, :method => 'delete', :data => { :confirm => "Are you sure?" } %>
</p>

<%= image_tag @artist.image, :class => 'portrait' %>
<ul>
  <li>Nationality: <%= @artist.nationality %></li>
  <li>Date of birth: <%= @artist.dob.strftime('%A %B %e, %Y') %></li>
  <li>Period: <%= @artist.period %></li>
</ul>

<% if @artist.works.any? %>
  <h2>Works</h2>
<% end %>

<% @artist.works.each do |work| %>
  <%= link_to(image_tag(work.image, :class => 'thumb'), work) %>
<% end %>